### Makefile.inc -- Project Lemonade Sqlite

# Lemonade Sqlite (https://github.com/michipili/lemonade-sqlite)
# This file is part of Lemonade Sqlite
#
# Copyright © 2016 Michael Grünewald
#
# This file must be used under the terms of the CeCILL-B.
# This source file is licensed as described in the file COPYING, which
# you should have received as part of this distribution. The terms
# are also available at
# http://www.cecill.info/licences/Licence_CeCILL-B_V1-en.txt

ODOC_TITLE=		Monadic Sqlite bindings

ODOC_HTML_CSS_FILE=	${PROJECTLIBRARY}/Data/ocamldoc.css
ODOC_HTML_CHARSET=	utf-8

# Local Variables:
# mode: makefile
# End:

### End of file `Makefile.inc'
